CREATE DATABASE IF NOT EXISTS adesh;
USE adesh;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chats (
  id VARCHAR(100) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  messages JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chats_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);